stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker build -t point_app .

deploy-job:
  stage: deploy
  environment:
    name: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - main
