# Generated by Django 5.1 on 2024-08-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdetails_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sub_category', to='appdetails_app.appcategory'),
        ),
        migrations.DeleteModel(
            name='AppSubCategory',
        ),
    ]
