# Generated by Django 5.1 on 2024-08-13 21:50

import appdetails_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdetails_app', '0002_alter_app_sub_category_delete_appsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(upload_to=appdetails_app.models.upload_to),
        ),
    ]
